spring:
    application:
        name: api-gateway

#API gateway config
    cloud:
        gateway:
            routes:
              - id: order-service
                uri: lb://ORDER-SERVICE
                predicates:
                    - Path=/orders/**
                    - Method = GET, POST
                filter:

              - id: inventory-service
                uri: lb://INVENTORY-SERVICE
                predicates:
                    - Path=/inventory/**

