spring.application.name=customer-service

spring.server.port=7411



#setting up the database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ms_customerservice
spring.datasource.username=puru
spring.datasource.password=puru

#Hibernate configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#setting up devtools settings
spring.devtools.restart.enabled=true