spring.application.name=inventory-service


#DevTools
spring.devtools.restart.enabled=true

#Database Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ms_inventoryservice
spring.datasource.username=puru
spring.datasource.password=puru

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate set-up
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.data-location=classpath:data.sql
spring.sql.init.mode=always

#Fix the one
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

