spring.application.name=inventory-service


#DevTools
spring.devtools.restart.enabled=true

#Database Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ms-orderservice
spring.datasource.username=puru
spring.datasource.password=puru